
openapi: 3.0.0
      info:
        title: Customer Service API
        description: Manages Customers.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /customers:
              post:
                  summary: Create Customer
                  description: Creates a customer.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/Customer'
                  responses:
                      '201':
                          description: Customer Created
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Customer'
      components:
          schemas:
              Customer:
                  type: object
                  properties:
                      id:
                          type: integer
                          description: The customer id.
                      first_name:  
                          type: string
                          description: The customer's first name.
                      last_name:  
                          type: string
                          description: The customer's last name.
                      email:  
                          type: string
                          format: email
                          description: The customer's email address.
                      date_of_birth:  
                          type: string
                          format: date
                          description: The customer's date of birth.
                      ssn:  
                          type: string
                          description: The customer's social security number.
                      address_line1:  
                          type: string
                          description: The first line of the customer's address.
                      address_line2:  
                          type: string
                          description: The second line of the customer's address.
                      city:  
                          type: string
                          description: The city of the customer's address.
                      state:  
                          type: string
                          description: The state of the customer's address.
                      zip_code:  
                          type: string
                          description: The zip code of the customer's address.
                      country:  
                          type: string
                          description: The country of the customer's address.
