
openapi: 3.0.0
      info:
        title: Customer API
        description: Manages Customers.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /customers:
              post:
                  summary: Create Customer
                  description: Creates a customer.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/Customer'
                  responses:
                      '201':
                          description: Customer Created
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Customer'
          /customers/verify_email:
              patch:
                  summary: Verify Email
                  description: Verifies a customer's email address.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/VerifyEmail'
                  responses:
                      '200':
                          description: Email Verified
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Customer'
      components:
          schemas:
              Customer:
                  type: object
                  properties:
                      id:
                          type: integer
                          description: The customer id.
                      first_name:
                          type: string
                          description: The customer's first name.
                      last_name:
                          type: string
                          description: The customer's last name.
                      email:
                          type: string
                          format: email
                          description: The customer's email address.
                      password:
                          type: string
                          format: password
                          description: The customer's password.
              VerifyEmail:
                  type: object
                  properties:
                      email:
                          type: string
                          format: email
                          description: The customer's email address.
                      password:
                          type: string
                          format: password
                          description: The customer's password.  
