
openapi: 3.0.0
      info:
        title: Customer API
        description: Manages Customers.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /customers:
              post:
                  summary: Create Customer
                  description: Creates a customer.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/Customer'
                  responses:
                      '201':
                          description: Customer Created
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Customer'
      components:
          schemas:
              Customer:
                  type: object
                  properties:
                      id:
                          type: integer
                          description: The customer id.
                      first_name:
                          type: string
                          description: The first name.
                      last_name:
                          type: string
                          description: The last name.
                      email:
                          type: string
                          format: email
                          description: The email.
                      date_of_birth:
                          type: string
                          format: date
                          description: The date of birth.
                      address_line1:
                          type: string
                          description: The address line 1.
                      address_line2:
                          type: string
                          description: The address line 2.
                      city:
                          type: string
                          description: The city.
                      state:
                          type: string
                          description: The state.
                      zip_code:
                          type: string
                          description: The zip code.
                      country:
                          type: string
                          description: The country.
