
openapi: 3.0.0
      info:
        title: Customer Service API
        description: Manages Customer Data.
        version: 1.0.0
      servers:
          - url: http://customerservice.example.com
      paths:
          /customers/reset:
              get:
                  summary: Validate Password Reset Token
                  description: Validates a password reset token.
                  parameters:
                      - in: query
                        name: token
                        schema:
                            type: string
                        required: true
                  responses:
                      '200':
                          description: Token Valid
                          content:
                              application/json:
                                  schema: {}
                      '404':
                          description: Invalid Token
                          content:
                              application/json:
                                  schema: {}
              patch:
                  summary: Update Customer Password
                  description: Updates a customer's password.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/UpdatePassword'
                  responses:
                      '200':
                          description: Password Updated
                          content:
                              application/json:
                                  schema: {}
      components:
          schemas:
              UpdatePassword:
                  type: object
                  properties:
                      password:
                          type: string
                          description: The new password.
                      customer_id:
                          type: integer
                          description: The customer id.
