
openapi: 3.0.0
      info:
        title: Fulfillment API
        description: Manages Order Fulfillments.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /fulfillments:
              post:
                  summary: Create Fulfillment
                  description: Creates a fulfillment.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/Fulfillment'
                  responses:
                      '201':
                          description: Fulfillment Created
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Fulfillment'
      components:
          schemas:
              Fulfillment:
                  type: object
                  properties:
                      fulfillment_id:
                          type: integer
                          description: The fulfillment id.
                      order_id:
                          type: integer
                          description: The order id.
                      tracking_number:
                          type: string
                          description: The tracking number.
                      fulfillment_status:
                          type: string
                          description: The fulfillment status.
