
openapi: 3.0.0
      info:
        title: Identity Service API
        description: Manages customer identities and authentication.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /customers/reset_password:
              post:
                  summary: Reset Customer Password
                  description: Resets a customer's password.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/ResetPasswordRequest'
                  responses:
                      '200':
                          description: Password Reset
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/ResetPasswordResponse'
      components:
          schemas:
              ResetPasswordRequest:
                  type: object
                  properties:
                      customer_id:
                          type: integer
                          description: The customer id.
                      reset_token:
                          type: string
                          description: The password reset token.
                      new_password:
                          type: string
                          description: The new password.
              ResetPasswordResponse:
                  type: object
                  properties:
                      message:
                          type: string
                          description: Success message.
