
openapi: 3.0.0
      info:
        title: Order Service API
        description: Manages Orders.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /orders/{order_id}:
              patch:
                  summary: Update Order Status
                  description: Updates the order status.
                  parameters:
                      - in: path
                        name: order_id
                        required: true
                        schema:
                            type: integer
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/OrderStatusUpdate'
                  responses:
                      '200':
                          description: Order Status Updated
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Order'
          /refunds:
              post:
                  summary: Process Refund
                  description: Processes a refund for an order.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/RefundRequest'
                  responses:
                      '200':
                          description: Refund Processed
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Refund'
      components:
          schemas:
              OrderStatusUpdate:
                  type: object
                  properties:
                      order_status:
                          type: string
                          description: The updated order status.
              RefundRequest:
                  type: object
                  properties:
                      order_id:
                          type: integer
                          description: The order id.
                      amount:
                          type: number
                          format: double
                          description: The refund amount.
              Refund:
                  type: object
                  properties:
                      refund_id:
                          type: integer
                          description: The refund id.
                      order_id:
                          type: integer
                          description: The associated order id.
                      amount:
                          type: number
                          format: double
                          description: The refund amount.
