
openapi: 3.0.0
      info:
        title: Order Service API
        description: Manages Orders.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /orders/{order_id}:
              patch:
                  summary: Process Return Request
                  description: Updates the order status to "Return Requested" and generates a return shipping label.
                  parameters:
                      - in: path
                        name: order_id
                        required: true
                        schema:
                            type: integer
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/ReturnRequest'
                  responses:
                      '200':
                          description: Order Updated
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Order'
      components:
          schemas:
              ReturnRequest:
                  type: object
                  properties:
                      order_status:
                          type: string
                          enum: 
                              - Return Requested
                      customer_email:
                          type: string
                          format: email
                          description: The customer's email address.
              Order:
                  type: object
                  properties:
                      order_id:
                          type: integer
                          description: The order id.
                      customer_id:
                          type: integer
                          description: The customer id.
                      order_date:
                          type: string
                          format: date-time
                          description: The order date.
                      order_total:
                          type: number
                          format: double
                          description: The order total.
                      order_status:
                          type: string
                          description: The order status.
