
openapi: 3.0.0
      info:
        title: Process Return API
        description: Processes customer returns.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /returns/{order_id}:
              patch:
                  summary: Process Return
                  description: Processes a customer return.
                  parameters:
                      - in: path
                        name: order_id
                        required: true
                        schema:
                            type: integer
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/ReturnRequest'
                  responses:
                      '200':
                          description: Return Processed
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Order'
      components:
          schemas:
              ReturnRequest:
                  type: object
                  properties:
                      order_status:
                          type: string
                          enum: 
                              - Return Requested
                              - Return Complete
                      amount:
                          type: number
                          format: double
                          description: The refund amount.
              Order:
                  type: object
                  properties:
                      order_id:
                          type: integer
                          description: The order id.
                      customer_id:
                          type: integer
                          description: The customer id.
                      order_date:
                          type: string
                          format: date-time
                          description: The order date.
                      order_total:
                          type: number
                          format: double
                          description: The order total.
                      order_status:
                          type: string
                          description: The order status.
