
openapi: 3.0.0
      info:
        title: Product API
        description: Manages Products.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /products/{id}:
              get:
                  summary: Get Product
                  description: Gets a product.
                  parameters:
                      - in: path
                        name: id
                        required: true
                        schema:
                            type: integer
                  responses:
                      '200':
                          description: Product Retrieved
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/Product'
      components:
          schemas:
              Product:
                  type: object
                  properties:
                      id:
                          type: integer
                          description: The product id.
                      name:
                          type: string
                          description: The product name.
                      description:
                          type: string
                          description: The product description.
                      price:
                          type: number
                          format: double
                          description: The product price.
                      image_url:
                          type: string
                          description: The product image URL.
