
openapi: 3.0.0
      info:
        title: Return API
        description: Manages Returns.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /returns:
              post:
                  summary: Create Return Request
                  description: Creates a return request.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/ReturnRequest'
                  responses:
                      '201':
                          description: Return Request Created
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/ReturnRequest'
          /returns/{return_id}/shipped:
              put:
                  summary: Mark Return as Shipped
                  description: Marks a return request as shipped.
                  parameters:
                      - in: path
                        name: return_id
                        required: true
                        schema:
                            type: integer
                  responses:
                      '200':
                          description: Return Request Updated
      components:
          schemas:
              ReturnRequest:
                  type: object
                  properties:
                      return_id:
                          type: integer
                          description: The return request id.
                      order_id:
                          type: integer
                          description: The order id.
                      item_ids:
                          type: array
                          items:
                              type: integer
                              description: The item ids being returned.
                      return_status:
                          type: string
                          description: The return request status.
