
openapi: 3.0.0
      info:
        title: Return API
        description: Manages Product Returns.
        version: 1.0.0
      servers:
          - url: http://localhost:8080
      paths:
          /returns:
              post:
                  summary: Create Return Request
                  description: Creates a return request.
                  requestBody:
                      required: true
                      content:
                          application/json:
                              schema:
                                  $ref: '#/components/schemas/ReturnRequest'
                  responses:
                      '201':
                          description: Return Request Created
                          content:
                              application/json:
                                  schema:
                                      $ref: '#/components/schemas/ReturnRequest'
      components:
          schemas:
              ReturnRequest:
                  type: object
                  properties:
                      return_id:
                          type: integer
                          description: The return id.
                      order_id:
                          type: integer
                          description: The order id.
                      reason:
                          type: string
                          description: The reason for the return.
                      return_status:
                          type: string
                          description: The return status.
